### PR TITLE
Thirdperson improvement and menu pagination adjusted

### PR DESCRIPTION
**Pull request by MartLegion**
Added thirdperson view after selecting a model from !lmc command
+New cvar lmc_thirdpersontime (default 2.0)

Menu pagination now stays after selecting a model from !lmc command
+New client variable iCurrentPage

I'm not pulling the .smx files, just the source (.sp).

### CODE REVIEW

**Comment by LuxLuma** [comment]
Hey thanks Ill give it a look later today, 
Just for reference could you link silvers hats and thirdperson plugin ill take a look at them later too to see how they work.

Thanks.

**Comment by MartLegion** [comment]
Link reference:

[L4D & L4D2] Hats
https://forums.alliedmods.net/showthread.php?p=1441080

[L4D2] Survivor Thirdperson
https://forums.alliedmods.net/showthread.php?p=1712767

**Comment by LuxLuma** [comment]
This is just a copy of the commit Description.

I'v made some changes to code to keep mostly consistent.

There is currenly a bug that causes some stuff to not render correctly, i'v fix this in LMC it seems to do with models that include particles, like the witch eye particles.

This is not true for the hats plugin and the thirdperson plugins by silvers doing the same thing while LMC model is witch, it can cause issue with rendering.

Ill make somechanges to silvers plugins and change the hacky thirdperson to something more easer for other plugins to play with.

Thanks for pull request, the menu is working great thanks :D

Ill do more testing and play with silver'ss plugins somemore.

Thanks.

image

**Comment by MartLegion** [comment]
I made the changes, but it seems I did not pay attention to some parts of the code. Thanks for correcting, it's very good now.

I got some stuff from the plugin I'm doing (not released yet) so it was not 100%.

I'm also against the hard code of the third person time, maybe you can talk to Silvers, the last time I spoke to him, he was not so friendly.

Maybe you should recode the "ShowMenuCmd" part, I cloned the Method ("ShowMenu") just to set the paging on "!lmc" command to 0. I'm sure it's not the best way to do this.

**Comment by LuxLuma** [comment]
I made commit some changes for more testing.
I have some progess on the rendering bug, this is a client bug however this only happens on map where i'v modded the "func_precipitation" entity, i'm unsure of the cause it maybe dues to how the gameworks with the bounds of the entity for the effects.

I made some changes to silvers plugin to prevent spamming, the thirdperson detection in the hats could use some work not sure if ill invest time into something i don't use.

[L4D2] Survivor Thirdperson
https://forums.alliedmods.net/showthread.php?p=1712767
```
public Action CmdThird(int client, int args)
{
	// if( client && GetClientTeam(client) == 2 && IsPlayerAlive(client) )
	if( client && IsPlayerAlive(client) )
	{
		static float fClientCmdCooldown[MAXPLAYERS+1];// help maybe.
		float fNow = GetEngineTime();
		if(fClientCmdCooldown[client] > fNow)
		{
			PrintToChat(client, "%s%s %i", CHAT_TAG, "Cooldown Expires in", RoundToCeil(fClientCmdCooldown[client] - fNow));
			return Plugin_Handled;
		}
		
		// Goto third
		if( g_bThirdView[client] == false )
		{
			g_bThirdView[client] = true;
			SetEntPropFloat(client, Prop_Send, "m_TimeForceExternalView", 99999.3);
			PrintToChat(client, "%s%t", CHAT_TAG, "On");
		}
		// Goto first
		else
		{
			g_bThirdView[client] = false;
			SetEntPropFloat(client, Prop_Send, "m_TimeForceExternalView", GetGameTime() + 1.0);// this will help other plugins.
			PrintToChat(client, "%s%t", CHAT_TAG, "Off");
		}
		fClientCmdCooldown[client] = fNow + 2.5;
	}

	return Plugin_Handled;
}
```

[L4D & L4D2] Hats
https://forums.alliedmods.net/showthread.php?p=1441080
```
void ExternalView(int client)
{
	if( g_fCvarChange )
	{
		EventView(client, false);
		
		if( g_hTimerView[client] != null )
			delete g_hTimerView[client];
		
		if( g_fCvarChange >= 2.0 )
			g_hTimerView[client] = CreateTimer(g_fCvarChange + 0.4, TimerEventView, GetClientUserId(client));
		else
			g_hTimerView[client] = CreateTimer(g_fCvarChange + 0.2, TimerEventView, GetClientUserId(client));
		
		// Survivor Thirdperson plugin sets 99999.3.
		float fCurrentTPtime = GetEntPropFloat(client, Prop_Send, "m_TimeForceExternalView");
		float fTime = GetGameTime();
		
		if(fCurrentTPtime > fTime + g_fCvarChange)
			return;
		
		if(fCurrentTPtime < fTime + 0.5)
		{
			if(fCurrentTPtime > fTime - 1.0)
				return;
		}
		
		SetEntPropFloat(client, Prop_Send, "m_TimeForceExternalView", fTime + g_fCvarChange);
	}
}
```

> I'm also against the hard code of the third person time, maybe you can talk to Silvers, the last time I spoke to him, he was not so friendly.

I was not talking about the hard coding sorry, there is no better way than setting the value high, i was talking about the detection in the hats plugin
`99999.3` getting this number i thought it was hacky and limited.

**Pull request merged**
